#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_get_app_settings_in_result_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_app_settings_in_result",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(mirror_ApplicationSettings(get_app_settings_in_result()?)),
    )
}
fn wire_get_vector_of_app_settings_impl(
    port_: MessagePort,
    count: impl Wire2Api<usize> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_vector_of_app_settings",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_count = count.wire2api();
            move |task_callback| {
                get_vector_of_app_settings(api_count)
                    .into_iter()
                    .map(|v| Ok(mirror_ApplicationSettings(v)))
                    .collect::<Vec<_>>()
            }
        },
    )
}
// Section: wrapper structs

#[derive(Clone)]
struct mirror_ApplicationEnv(ApplicationEnv);

#[derive(Clone)]
struct mirror_ApplicationEnvVar(ApplicationEnvVar);

#[derive(Clone)]
struct mirror_ApplicationMode(ApplicationMode);

#[derive(Clone)]
struct mirror_ApplicationSettings(ApplicationSettings);

// Section: static checks

const _: fn() = || {
    {
        let ApplicationEnv = None::<ApplicationEnv>.unwrap();
        let _: Vec<ApplicationEnvVar> = ApplicationEnv.vars;
    }
    {
        let ApplicationEnvVar_ = None::<ApplicationEnvVar>.unwrap();
        let _: String = ApplicationEnvVar_.0;
        let _: bool = ApplicationEnvVar_.1;
    }
    match None::<ApplicationMode>.unwrap() {
        ApplicationMode::Standalone => {}
        ApplicationMode::Embedded => {}
    }
    {
        let ApplicationSettings = None::<ApplicationSettings>.unwrap();
        let _: String = ApplicationSettings.name;
        let _: String = ApplicationSettings.version;
        let _: ApplicationMode = ApplicationSettings.mode;
        let _: Box<ApplicationEnv> = ApplicationSettings.env;
        let _: Option<ApplicationEnv> = ApplicationSettings.env_optional;
    }
};
// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}
impl Wire2Api<usize> for usize {
    fn wire2api(self) -> usize {
        self
    }
}
// Section: impl IntoDart

impl support::IntoDart for mirror_ApplicationEnv {
    fn into_dart(self) -> support::DartAbi {
        vec![self
            .0
            .vars
            .into_iter()
            .map(|v| mirror_ApplicationEnvVar(v))
            .collect::<Vec<_>>()
            .into_dart()]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_ApplicationEnv {}

impl support::IntoDart for mirror_ApplicationEnvVar {
    fn into_dart(self) -> support::DartAbi {
        vec![self.0 .0.into_dart(), self.0 .1.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_ApplicationEnvVar {}

impl support::IntoDart for mirror_ApplicationMode {
    fn into_dart(self) -> support::DartAbi {
        match self.0 {
            ApplicationMode::Standalone => 0,
            ApplicationMode::Embedded => 1,
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_ApplicationMode {}
impl support::IntoDart for mirror_ApplicationSettings {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.0.name.into_dart(),
            self.0.version.into_dart(),
            mirror_ApplicationMode(self.0.mode).into_dart(),
            mirror_ApplicationEnv((*self.0.env)).into_dart(),
            self.0
                .env_optional
                .map(|v| mirror_ApplicationEnv(v))
                .into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for mirror_ApplicationSettings {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
